name: sadbox.org build, test, and maybe push

on:
  push:
    branches-ignore: # Dependabot branches get ran through pull_request
      - 'dependabot/**'
  pull_request:
  schedule:
    - cron: '0 5 * * 1,3,5'

jobs:
  publish-latest:
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sadbox/sadbox-web:latest
          target: prod
          platforms: linux/amd64,linux/arm64
